# Checks that we can build and validate the Unittest
name: Pull-Request-Checks

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      #- name: Install Poetry
      #  uses: actions/checkout@v2
#	with:
#	  python-version: 3.7
#	uses: Gr1N/setup=poetry@v7
#	run: poetry --version

      #- name: Cache Poetry virtualenv
      #  uses: actions/cache@v1
      #  id: cache
      #  with:
      #    path: ~/.virtualenvs
      #    key: poetry-$
      #    restore-keys: |
      #      poetry-$